dewaldreynecke/betterme

app/controllers/entries_controller.rb, app/models/activity.rb, app/views/entries/new.html.erb, app/views/entries/newguided.html.erb, config/routes.rb, db/migrate/20230606150939_remove_user_from_activity.rb, db/migrate/20230606152701_remove_type_from_entries.rb, db/migrate/20230606152824_add_title_to_entries.rb, db/schema.rb, db/seeds.rb, yarn.lock
This includes some changes to the database which have become necessary after our design sprint.
- Remove user reference from Activity (still there from when it was Tags, but now that Activities are global it is a roadblock)
- Remove Type column from Entries since it won't be used anymore with our unified journal entry user journey.
- Add Title to Entries to support the title field added to the New page.
- Create seed for User (only demo user), Activity, and Prompts.
- Update routes to facilitate journal creation, but this will change again in a future PR with the unified New page.
- Update Entries Controller with paths for the different New pages – again this will change in future once the page is unified.
- Create basic structure on New page. Incomplete.
=> Update database for new app structure

app/views/pages/_banner.html.erb, app/views/pages/dashboard.html.erb
Continued with the layout of the dashboard. Not yet completed.
=> Further progress on Dashboard layout

app/controllers/entries_controller.rb, app/controllers/inspirations_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/inspiration_controller.js, app/views/entries/_banner.html.erb, app/views/inspirations/_inspiration.html.erb, app/views/inspirations/random.html.erb, config/routes.rb, test/controllers/inspirations_controller_test.rb
Added function to refresh the Inspiration message in the banner of the NEW page when you press the button. It fetches a random new one from the database with AJAX and replaces it on the page without a reload.
There are only 3 inspirations in the database – we need to add many more to lower the chances of receiving the same message.
=> Feature: inspiration refresh

app/controllers/pages_controller.rb, app/controllers/user_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/theme_controller.js, app/views/pages/_banner.html.erb, app/views/user/update.html.erb, config/routes.rb, test/controllers/user_controller_test.rb
Adds the ability to change your theme right in the banner on the dashboard.
=> Feature: theme change

app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb
Wrap all the Devise views into Bootstrap .container DIV.
=> Style Devise views

db/seeds.rb
Added addresses around western cape to the seed file
=> Added addresses to seed

app/controllers/moods_controller.rb, app/controllers/pages_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/mood_controller.js, app/views/pages/_awesome.html.erb, app/views/pages/_bad.html.erb, app/views/pages/_happy.html.erb, app/views/pages/_mood.html.erb, app/views/pages/_okay.html.erb, app/views/pages/_terrible.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
This implements the feature where you can choose your mood on the dashboard
- Creates mood chooser partial.
- Creates partials for the five moods.
- Implements Stimulus/AJAX behaviour to change the mood card when you choose the mood.
- Saves the chosen mood to the database in the controller.
TODO (I have made cards in the Trello for these)
- set the mood on the dashboard first load if a mood was already chosen for today
- make sure the seed does not have a mood set for demo day
=> Feature: set mood

app/assets/stylesheets/components/_image_scroll.scss, app/controllers/entries_controller.rb, app/views/entries/show_by_date.html.erb
styling changes - background color 
rounded edges 
next and previous features
=> Entry show

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
Add sticky footer.
No styling applied for font-family or colour - trust this will pull through when we set the Bootstrap overrides.
=> Add footer

app/views/shared/_navbar.html.erb
Fixes BETTERME title in navbar to link to the dashboard page.
=> Fix: navbar link

public/404.html, public/422.html, public/500.html
Error pages given custom style.
=> Error pages: custom style

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_dashboard_mood.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/pages/_banner.html.erb, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb
Corrected errors for app to work
=> Styling mood tracker

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_moodcard.scss, app/views/pages/_banner.html.erb, app/views/pages/_mood.html.erb
Changed the layout of the banner and the color of the moodcard to reflect the figma
=> Banner layout and mood-picker color changed

app/controllers/entries_controller.rb, app/controllers/pages_controller.rb, app/controllers/themes_controller.rb, app/views/pages/dashboard.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
Shows today's mood on the dashboard and as the Navbar avatar when the user has already chosen one – if not the chooser is displayed.
=> Feature: show current mood

app/assets/stylesheets/pages/_profile.scss, app/controllers/addresses_controller.rb, app/controllers/pages_controller.rb, app/views/pages/profile.html.erb
Add the ability to add and remove _Saved Addresses_ on the profile page.
=> Feature: Profile address edit

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/pages/_entry_new.scss, app/javascript/controllers/favourite_address_controller.js, app/views/entries/new.html.erb
Saved address buttons now activate the one you clicked on as it should be.
Updated styling of all buttons on page to our new style.
=> Fix address buttons

app/javascript/controllers/inspiration_controller.js, package.json, yarn.lock
Add a Javascript typing effect on the new entry page when you request a new inspiration.
=> Feature: inspiration typing

app/assets/stylesheets/components/_entry_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/pages_controller.rb, app/views/entries/_entry_card.erb, app/views/entries/show_by_date.html.erb, app/views/pages/dashboard.html.erb, app/views/themes/show.html.erb
**Update the entry card**
- Entry card is now a partial.
- Card now displays placeholder photo in case of no photos, or single photo, or auto carousel of multiple photos attached to entry.
- Date display on card reformatted.
- Location display on card is hidden in case there is no address.
- Card body scrolls in case there is more text in the content than will fit.
- Used partial on Show-by-date and Themes#show.
- Added two most recent entries to dashboard.
A preview of what it looks like now. Placeholder image on left.
=> Style: entry card

app/assets/stylesheets/components/_entry_card.scss, app/assets/stylesheets/pages/_entry_new.scss, app/javascript/controllers/favourite_address_controller.js, app/javascript/controllers/tagtoggle_controller.js, app/views/entries/_entry_card.html.erb, app/views/entries/new.html.erb, app/views/entries/show_by_date.html.erb, app/views/pages/dashboard.html.erb, app/views/themes/show.html.erb
**This expands the Tags feature**
- A user can only see their own tags
- A user can add and remove tags on their profile page
- A user can add one or more of the saved tags to a journal entry by selecting them on the NEW page
- Tags associated with an entry displays on the entry_card partial wherever it is displayed
- Changes the layout of the new entry page to expand the content box by moving the submit button to the right
Adding the Tags on the new page
Displaying them on the Entry Card
=> Feature: Tags

app/controllers/tags_controller.rb, app/views/entries/_entry_card.html.erb, app/views/pages/profile.html.erb, app/views/tags/show.html.erb, db/migrate/20230615103041_add_deleted_to_tags.rb, db/schema.rb
User now cannot delete tags anymore.
Tags on cards are now links to a show page where all entries related to the tag are displayed.
=> Refine tags

app/javascript/controllers/calendar_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/mood_controller.js, app/views/pages/_calendar.html.erb, app/views/pages/dashboard.html.erb
Changes the calendar colour for today when you choose your mood (without a page reload).
=> Change mood on calendar via JS

app/assets/stylesheets/components/_home_banner.scss, app/views/pages/home.html.erb
Chnaged src tags to image helpers on html and modified also for the home-banner with ruby code
=> changed image tags

app/assets/stylesheets/components/_chart.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_moodcard.scss, app/views/pages/_awesome.html.erb, app/views/pages/_bad.html.erb, app/views/pages/_happy.html.erb, app/views/pages/_mood.html.erb, app/views/pages/_okay.html.erb, app/views/pages/_terrible.html.erb, app/views/pages/dashboard.html.erb, app/views/shared/_mood_chart.html.erb
General layout and styling upgrades.
=> Styling dashboard

app/assets/stylesheets/pages/_confirmation.scss, app/views/pages/confirmation.html.erb
=> Styling: confirmation page

app/views/pages/home.html.erb
Fixed image tags on home page – through some merge mess they reverted.
=> Change img tags to image_tag helpers

db/seeds.rb
Update seed so that it can run without having to drop and recreate the database first (for Heroku).
=> Fix cleanup routine at start of seed

app/assets/stylesheets/pages/_moodcard.scss
Changes styling of the moodbox so that the shadow matches the other boxes on the dashboard.
=> Moodbox shadow

app/assets/stylesheets/pages/_confirmation.scss, app/views/pages/confirmation.html.erb, app/views/pages/home.html.erb
Updated opacity of header image on home page.
Changed font sizes on confirmation page.
=> Demo refine

app/javascript/controllers/map_controller.js
Changed the map to zoom once reloaded
=> Adjusted the zoom on the map

app/assets/stylesheets/components/_devise_forms.scss, app/assets/stylesheets/components/_index.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/unlocks/new.html.erb
Fixes #98 
- Create new styles for the primary button on the Devise views.
- Create new style for the _Remember Me_ button on the login page to align it with the other form controls.
- Add the new classes to the primary buttons on all Devise views.
=> Style devise buttons

app/assets/stylesheets/components/_entry_card.scss, app/views/entries/_entry_card.html.erb, app/views/entries/show_by_date.html.erb, app/views/entries/show_by_location.html.erb, app/views/pages/dashboard.html.erb, app/views/pages/search.html.erb, app/views/tags/show.html.erb, app/views/themes/show.html.erb
Fixes #97 
- Refactor the __entry_card_ partial to take an entry object as local variable.
- Update all views that call the entry card to pass the expected local variable.
- Make location text on __entry_card_ a link and style it.
=> 97 clickable location text on entry card
